stages:
  - build docker image
  - push docker hub

build:
  stage: build docker image
  image: docker:latest
  script:
    - docker info
    - docker build --network br_docker --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} .

push:
  stage: push docker hub
  image: docker:latest
  only:
    - master
  script:
    - echo ${REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
